// generated with ast extension for cup
// version 0.8
// 14/11/2024 11:22:34


package rs.ac.bg.etf.pp1.ast;

public interface Visitor { 

    public void visit(DeclarationList DeclarationList);
    public void visit(Mulop Mulop);
    public void visit(ConstantList ConstantList);
    public void visit(Relop Relop);
    public void visit(Constants Constants);
    public void visit(DesignatorElem DesignatorElem);
    public void visit(StatementList StatementList);
    public void visit(NamespaceList NamespaceList);
    public void visit(Addop Addop);
    public void visit(Factor Factor);
    public void visit(Designator Designator);
    public void visit(Term Term);
    public void visit(Brackets Brackets);
    public void visit(VarDeclList VarDeclList);
    public void visit(FormalParamList FormalParamList);
    public void visit(VarDeclarationList VarDeclarationList);
    public void visit(Expr Expr);
    public void visit(ActPars ActPars);
    public void visit(MethodTypeName MethodTypeName);
    public void visit(DesignatorStatement DesignatorStatement);
    public void visit(Statement Statement);
    public void visit(ActParamList ActParamList);
    public void visit(Type Type);
    public void visit(MethodDeclList MethodDeclList);
    public void visit(FormPars FormPars);
    public void visit(MulopMod MulopMod);
    public void visit(MulopDiv MulopDiv);
    public void visit(MulopMul MulopMul);
    public void visit(AddopMinus AddopMinus);
    public void visit(AddopPlus AddopPlus);
    public void visit(RelopMore RelopMore);
    public void visit(RelopLess RelopLess);
    public void visit(RelopLArrow RelopLArrow);
    public void visit(RelopRArrow RelopRArrow);
    public void visit(RelopNotEqual RelopNotEqual);
    public void visit(RelopEqual RelopEqual);
    public void visit(Assignop Assignop);
    public void visit(Label Label);
    public void visit(NoDesElem NoDesElem);
    public void visit(DesElem DesElem);
    public void visit(DesWithIdent DesWithIdent);
    public void visit(Des Des);
    public void visit(FactorDes FactorDes);
    public void visit(FactorExpr FactorExpr);
    public void visit(FactorNew FactorNew);
    public void visit(FactorChar FactorChar);
    public void visit(FactorNum FactorNum);
    public void visit(TermFactor TermFactor);
    public void visit(TermMulop TermMulop);
    public void visit(ExprMinusTerm ExprMinusTerm);
    public void visit(ExprTerm ExprTerm);
    public void visit(ExprAddop ExprAddop);
    public void visit(ActParamExpr ActParamExpr);
    public void visit(ActParamsList ActParamsList);
    public void visit(NoActParams NoActParams);
    public void visit(ActParams ActParams);
    public void visit(DesignatorDecr DesignatorDecr);
    public void visit(DesignatorInc DesignatorInc);
    public void visit(DesginatorAssignop DesginatorAssignop);
    public void visit(DesStmt DesStmt);
    public void visit(ReadStmt ReadStmt);
    public void visit(PrintStmtTwo PrintStmtTwo);
    public void visit(PrintStmt PrintStmt);
    public void visit(NoStmtList NoStmtList);
    public void visit(StmtList StmtList);
    public void visit(NoTypes NoTypes);
    public void visit(Types Types);
    public void visit(NoBracket NoBracket);
    public void visit(Bracket Bracket);
    public void visit(FormalParamDecl FormalParamDecl);
    public void visit(FormalParsDecl FormalParsDecl);
    public void visit(FormalParsList FormalParsList);
    public void visit(NoFormalPars NoFormalPars);
    public void visit(FormalPars FormalPars);
    public void visit(NoMethTypeName NoMethTypeName);
    public void visit(MethTypeName MethTypeName);
    public void visit(MethodDecl MethodDecl);
    public void visit(NoMethDeclList NoMethDeclList);
    public void visit(MethDeclList MethDeclList);
    public void visit(VarDeclaration VarDeclaration);
    public void visit(VarDeclarat VarDeclarat);
    public void visit(VarDeclaratList VarDeclaratList);
    public void visit(VarDecl VarDecl);
    public void visit(NoVarDeclarList NoVarDeclarList);
    public void visit(VarDeclarList VarDeclarList);
    public void visit(CharConstant CharConstant);
    public void visit(NumConstant NumConstant);
    public void visit(NoConstList NoConstList);
    public void visit(ConstList ConstList);
    public void visit(ConstDeclList ConstDeclList);
    public void visit(NoDecLists NoDecLists);
    public void visit(VarDecLists VarDecLists);
    public void visit(ConstDecLists ConstDecLists);
    public void visit(Namespace Namespace);
    public void visit(NoNameList NoNameList);
    public void visit(NameList NameList);
    public void visit(ProgName ProgName);
    public void visit(Program Program);

}
