
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 13 16:10:20 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 40;
  public static final int RARROW = 35;
  public static final int LBRACKET = 32;
  public static final int CONST = 6;
  public static final int NAMESPACE = 17;
  public static final int AMPER = 37;
  public static final int LPAREN = 28;
  public static final int SEMI = 25;
  public static final int CONTINUE = 14;
  public static final int FOR = 15;
  public static final int MINUS = 19;
  public static final int STATIC = 16;
  public static final int RPAREN = 29;
  public static final int COMMA = 26;
  public static final int CLASS = 4;
  public static final int DIV = 20;
  public static final int PLUS = 18;
  public static final int IF = 7;
  public static final int DOT = 27;
  public static final int EXCL = 36;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 33;
  public static final int EQUAL = 23;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int LINE = 38;
  public static final int NUMBER = 39;
  public static final int MOD = 21;
  public static final int IDENT = 42;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int DBLDOT = 24;
  public static final int LBRACE = 30;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACE = 31;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 41;
  public static final int LARROW = 34;
  public static final int PRINT = 9;
}

